export { AuthProvider } from './AuthProvider'
export { useAuth, notifyLocalSessionChange } from './useAuth'
export { isAuthConfigured } from './msalConfig'
export { signUp, signIn } from './localAuth'
export type { AuthUser } from './useAuth'
