import type { AgentAdminRecord, OverviewSignal } from '@/types'

export const agentAdminRecords: Record<string, AgentAdminRecord> = {
  'agt-sales-triage': {
    publisher: 'Northwind Revenue Operations',
    availability: 'Published',
    catalogState: 'Requestable',
    assignment: 'Revenue Operations and sales managers',
    supportedApps: ['Teams', 'Microsoft 365 Copilot'],
    complianceState: 'In review',
    version: '1.8.2',
    capabilities: ['Lead qualification', 'Reply drafting'],
    knowledgeSources: ['CRM history', 'Forms intake', 'Account notes'],
    actions: ['Create lead', 'Request approval'],
    lifecycleStage: 'Production',
    metering: 'Included',
    requestOwner: 'Revenue operations admin',
    accessPolicy: 'Scoped to revenue managers and reviewers',
    lastReview: '11 Mar 2026',
    identityMode: 'Mixed',
    adminConsent: 'Scoped',
    permissions: ['CRM write', 'Mail draft', 'Forms read'],
  },
  'agt-fin-close': {
    publisher: 'Northwind Corporate Finance',
    availability: 'Limited release',
    catalogState: 'Hidden',
    assignment: 'Corporate Finance close leads',
    supportedApps: ['Microsoft 365 Copilot', 'Power Platform'],
    complianceState: 'Passed',
    version: '2.1.0',
    capabilities: ['Close summary generation', 'Variance follow-up'],
    knowledgeSources: ['Finance ledger', 'Close package workspace'],
    actions: ['Draft summary', 'Post analyst task'],
    lifecycleStage: 'Pilot',
    metering: 'Capacity pack',
    requestOwner: 'Finance controls board',
    accessPolicy: 'Finance close leads only',
    lastReview: '10 Mar 2026',
    identityMode: 'Delegated',
    adminConsent: 'Approved',
    permissions: ['Ledger read', 'Close package files'],
  },
  'agt-hr-onboard': {
    publisher: 'Northwind People Operations',
    availability: 'Requested',
    catalogState: 'Pending review',
    assignment: 'People Operations reviewers only',
    supportedApps: ['Teams'],
    complianceState: 'Restricted',
    version: '0.9.4',
    capabilities: ['Onboarding coordination', 'New hire Q&A'],
    knowledgeSources: ['Onboarding checklist', 'HR knowledge articles'],
    actions: ['Open onboarding task', 'Request profile data'],
    lifecycleStage: 'Validate',
    metering: 'Pay-as-you-go',
    requestOwner: 'People operations admin',
    accessPolicy: 'Request-only until HR and compliance approve',
    lastReview: '11 Mar 2026',
    identityMode: 'Delegated',
    adminConsent: 'Required',
    permissions: ['HR profile read', 'Checklist write'],
  },
  'agt-graph-sync': {
    publisher: 'Northwind Platform Engineering',
    availability: 'Private',
    catalogState: 'Hidden',
    assignment: 'Platform Engineering only',
    supportedApps: ['Microsoft Graph', 'Copilot Studio'],
    complianceState: 'Passed',
    version: '3.0.1',
    capabilities: ['Telemetry synchronization', 'Connector health checks'],
    knowledgeSources: ['Agent telemetry store', 'Connector diagnostics'],
    actions: ['Sync event batch', 'Open connector alert'],
    lifecycleStage: 'Develop',
    metering: 'Included',
    requestOwner: 'Platform engineering admin',
    accessPolicy: 'Private engineering workflow only',
    lastReview: '09 Mar 2026',
    identityMode: 'App-only',
    adminConsent: 'Approved',
    permissions: ['Telemetry read', 'Connector diagnostics'],
  },
}

export const agentOverviewSignals: Record<string, OverviewSignal> = {
  'agt-sales-triage': { publisherType: 'Organization', platform: 'Copilot Studio', ownerState: 'Assigned', usage7d: [32, 36, 34, 39, 42, 48, 45] },
  'agt-fin-close': { publisherType: 'Organization', platform: 'Microsoft 365 Agent Builder', ownerState: 'Assigned', usage7d: [8, 10, 9, 11, 12, 14, 13] },
  'agt-hr-onboard': { publisherType: 'Organization', platform: 'Copilot Studio', ownerState: 'Assigned', usage7d: [0, 1, 0, 2, 3, 2, 4] },
  'agt-graph-sync': { publisherType: 'Partner', platform: 'Azure AI Foundry', ownerState: 'Ownerless', usage7d: [4, 3, 5, 4, 6, 5, 4] },
}
